### ISSUE TITLE
Running javascript on new page

### ISSUE THREAD

**Issue by manelclos** [enyo/stateless-html-example#2]
After loading the new page, only the html is changed. How is the javascript for that page supposed to be executed?

**Comment by enyo** [comment]
You mean in case there is JS embedded in your html page?

Well.. I think that's not best practice. Ideally the JS is loaded for your page, and simply switches state in between your pages. (So you would have one `app` and that knows that you just switched from `news.html` to `about.html`, so it will invoke the appropriate setup functions)

If you depend on executing JS that is embedded in your page, there are a few unclean solutions to do so. You can checkout this stackoverflow question for example: http://stackoverflow.com/questions/1308330/executing-javascript-functions-from-an-ajax-html-response
